wandb_version: 1

dataset:
  desc: null
  value: Sprites
dataset_size:
  desc: null
  value: 100
max_epoch:
  desc: null
  value: 1000
wandb_project:
  desc: null
  value: reward_prediction_model
wandb_exp:
  desc: null
  value: test
weight_save_path:
  desc: null
  value: ./weights/
weight_save_interval:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
scheduler_gamma:
  desc: null
  value: 0.99
resolution:
  desc: null
  value: 64
max_seq_len:
  desc: null
  value: 30
max_speed:
  desc: null
  value: 0.05
obj_size:
  desc: null
  value: 0.2
shapes_per_traj:
  desc: null
  value: 2
rewards:
  desc: null
  value:
  - agent_y
  - agent_x
  - target_x
  - target_y
input_channels:
  desc: null
  value: 3
hidden_dim:
  desc: null
  value: 64
gpus:
  desc: null
  value: 0
use_wandb:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709038800.782151
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 4
      - 5
      13: darwin-arm64
